name: ci

on: push

jobs:
  build-upload-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - run: GOOS=linux GOARCH=amd64 go build -o main-${{ github.sha }} handler/main.go
      - uses: papeloto/action-zip@v1
        with:
          files: main-${{ github.sha }}
          dest: to-upload/main-${{ github.sha }}.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy zip to AWS S3
        run: aws s3 sync to-upload s3://hello-world-zip --delete

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: production
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
